project:
  type: book
  output-dir: docs
  preview:
    port: 6616

execute: 
  message: false
  warning: false
  
book:
  title: "Operations Research Primer"
  author: "Berk Orbay"
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - part: linprog.qmd
      chapters:
        - linmodel.qmd
        - giapetto.qmd
format:
  html:
    theme: cosmo
    html-math-method: mathjax
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            tex: {
              tags: 'ams'
            }
          };
          </script>
  pdf: 
    documentclass: scrreprt


